import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  public projects = [
    { project: 'SSM - Memora\'s Services Sistem', description: 'An internarl web application for handle request of user An internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of user', imagePath: 'https://github.com/LeonardoPaiv/frontend-profile/blob/master/src/assets/WhatsApp%20Image%202022-06-04%20at%2000.16.00.jpeg' },
    { project: 'SSM - Memora\'s Services Sistem', description: 'An internarl web application for handle request of user An internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of user', imagePath: '../../../../assets/WhatsApp Image 2022-06-04 at 00.16.00.jpeg' },
    { project: 'SSM - Memora\'s Services Sistem', description: 'An internarl web application for handle request of user An internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of user', imagePath: '../../../../assets/WhatsApp Image 2022-06-04 at 00.16.00.jpeg' },
    { project: 'SSM - Memora\'s Services Sistem', description: 'An internarl web application for handle request of user An internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of userAn internarl web application for handle request of user', imagePath: '../../../../assets/WhatsApp Image 2022-06-04 at 00.16.00.jpeg' }
  ]
}
